# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      PYVER: ${{ matrix.python-version }}
      PACKAGE: cg_openmm
      
    steps:
      - uses: actions/checkout@v2
     
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: test
          channel-priority: true
          environment-file: devtools/conda-envs/test_env.yaml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps .

      - name: Run tests
        shell: bash -l {0}
        run: |
          PYTEST_ARGS=" -v --cov=$PACKAGE --cov-report=xml --cov-config=setup.cfg"
          pytest $PYTEST_ARGS $PACKAGE

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
